In [60]:
import torch

# 向量
x = torch.arange(4) # 创建向量 只有第0维(设有4个元素) 注意要和一行n列的矩阵区分开(矩阵有第1维)
print(len(x)) # 访问向量的长度(元素个数)

#矩阵
y = x.reshape(2,2) # 把y设置为2*2的矩阵
print(y.numel()) # 访问张量的元素总个数
print(y.shape) # 矩阵在各个维(从0开始)上的长度
print(y,y.T)  # 矩阵的转置 .T

4
4
torch.Size([2, 2])
tensor([[0, 1],
        [2, 3]]) tensor([[0, 2],
        [1, 3]])


## 张量
> 就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。张量（本小节中的“张量”指代数对象）为我们提供了描述具有任意数量轴的 n 维数组的通用方法。例如，向量是一阶张量，矩阵是二阶张量。张量用特殊字体的大写字母（例如， `X` 、 `Y` 和 `Z` ）表示，它们的索引机制（例如 $x_{ijk}$）与矩阵类似。当我们开始处理图像时，张量将变得更加重要，图像以 `n` 维数组形式出现，其中3个轴对应于高度、宽度，以及一个通道（channel）轴，用于堆叠颜色通道（红色、绿色和蓝色）。

In [48]:
# 两个张量之间的运算
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B, A*B # 均为按元素操作运算

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [50]:
# 标量和张量之间的运算
a = 2
A,a + A, a*A  # 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [58]:
# 降维 即获得张量的一些统计数据

# 默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量
print(A, A.sum())  

# 指定沿某个轴来求和
A_sum_axis0 = A.sum(axis=0) # 沿0轴求和(竖直向下,把所有行求和 第0维压缩为一行)
print(A_sum_axis0.shape)  # 由于输入矩阵沿0轴降维以生成输出向量，因此输入的轴0的维数在输出形状中丢失。

# 指定多个降维的轴的顺序
A.sum(axis=[0, 1])  # Same as A.sum()



tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor(190.)
torch.Size([4])


tensor(190.)

In [68]:
# 常用统计
print(A)

# 均值
print(A.mean() == A.sum() / A.numel())

print(A.mean(axis = 0))




tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(True)
tensor([ 8.,  9., 10., 11.])


In [74]:
# 非降维求和 方便进行广播运算

sum_A = A.sum(axis=1, keepdims=True)  # 求和 但不降维 方便进行广播
print(A,'\n',sum_A,'\n', A / sum_A) # 求出每个元素占当前行总和的比重

A.cumsum(axis=0)  # 沿0轴计算A元素的累积总和 总和矩阵 


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]) 
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积
即给定两个向量(列向量是向量的默认方向), $\mathbf{x}, \mathbf{y} \in \mathbb{R}^{d}$，它们的点积为 $\mathbf{x}^{\top} \mathbf{y}$ ,也就是一行乘一列 得到的是一个数: $\mathbf{x}^{\top} \mathbf{y}=\sum_{i=1}^{d} x_{i} y_{i}$

In [88]:
y = torch.ones(4,dtype=torch.int64)
x,y,torch.dot(x,y) # 注意数据类型一致才能相乘

(tensor([0, 1, 2, 3]), tensor([1, 1, 1, 1]), tensor(6))

## 矩阵-向量积
即一个矩阵 $\mathbf{A} \in \mathbb{R}^{m \times n}$ 乘一个向量 $\mathbf{x} \in \mathbb{R}^{n}$，首先将矩阵行分块$
\mathbf{A}=\left[\begin{array}{c} 
\mathbf{a}_{1}^{\top} \\
\mathbf{a}_{2}^{\top} \\
\vdots \\
\mathbf{a}_{m}^{\top} \\
\end{array}\right]
$

则 

$
\mathbf{A} \mathbf{x}=\left[\begin{array}{c}
\mathbf{a}_{1}^{\top} \\
\mathbf{a}_{2}^{\top} \\
\vdots \\
\mathbf{a}_{m}^{\top}
\end{array}\right] \mathbf{x}=\left[\begin{array}{c}
\mathbf{a}_{1}^{\top} \mathbf{x} \\
\mathbf{a}_{2}^{\top} \mathbf{x} \\
\vdots \\
\mathbf{a}_{m}^{\top} \mathbf{x}
\end{array}\right]
$



In [97]:
x = torch.arange(4,dtype=torch.float32)
A,x,torch.mv(A,x) # 矩阵-向量积

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵乘法
对于两个矩阵 $=\mathbf{A} \in \mathbb{R}^{n \times k}$ 和 $\mathbf{B} \in \mathbb{R}^{k \times m}$ ：

$\mathbf{A}=\left[\begin{array}{cccc}a_{11} & a_{12} & \cdots & a_{1 k} \\ a_{21} & a_{22} & \cdots & a_{2 k} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n 1} & a_{n 2} & \cdots & a_{n k}\end{array}\right], \quad \mathbf{B}=\left[\begin{array}{cccc}b_{11} & b_{12} & \cdots & b_{1 m} \\ b_{21} & b_{22} & \cdots & b_{2 m} \\ \vdots & \vdots & \ddots & \vdots \\ b_{k 1} & b_{k 2} & \cdots & b_{k m}\end{array}\right]$

将$A$行分块，$B$列分快，则有：

$\mathbf{C}=\mathbf{A} \mathbf{B}=\left[\begin{array}{c}\mathbf{a}_{1}^{\top} \\ \mathbf{a}_{2}^{\top} \\ \vdots \\ \mathbf{a}_{n}^{\top}\end{array}\right]\left[\begin{array}{llll}\mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m}\end{array}\right]=\left[\begin{array}{cccc}\mathbf{a}_{1}^{\top} \mathbf{b}_{1} & \mathbf{a}_{1}^{\top} \mathbf{b}_{2} & \cdots & \mathbf{a}_{1}^{\top} \mathbf{b}_{m} \\ \mathbf{a}_{2}^{\top} \mathbf{b}_{1} & \mathbf{a}_{2}^{\top} \mathbf{b}_{2} & \cdots & \mathbf{a}_{2}^{\top} \mathbf{b}_{m} \\ \vdots & \vdots & \ddots & \vdots \\ \mathbf{a}_{n}^{\top} \mathbf{b}_{1} & \mathbf{a}_{n}^{\top} \mathbf{b}_{2} & \cdots & \mathbf{a}_{n}^{\top} \mathbf{b}_{m}\end{array}\right]$


In [101]:
B = torch.ones((4,3))
A,B,torch.mm(A,B) # 矩阵乘法

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

## 范数

一个向量的范数告诉我们一个向量有多大。 这里考虑的大小（size）概念不涉及维度，而是分量的大小

常用的范数为2范数
对于一个向量$x$ 则其2范数为向量元素平方和的平方根

$$
\|\mathbf{x}\|_{2}=\sqrt{\sum_{i=1}^{n} x_{i}^{2}}
$$

注：对于2范数，常常省略下标2

还有一个比较常用的为1范数，其为向量元素的绝对值之和:

$$
\|\mathbf{x}\|_{1}=\sum_{i=1}^{n}\left|x_{i}\right| .
$$

广义一般化 $p范数$：
$$
\|\mathbf{x}\|_{p}=\left(\sum_{i=1}^{n}\left|x_{i}\right|^{p}\right)^{1 / p}
$$

对于矩阵常用的范数为弗罗贝尼乌斯范数（Frobenius norm）：矩阵元素平方方和的平方根(类似于向量的2范数)

$$
\|\mathbf{X}\|_{F}=\sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} x_{i j}^{2}}
$$

In [108]:
u = torch.tensor([3.0, -4.0])
print(u,'\n',torch.norm(u)) # 计算向量的2范数
print(torch.abs(u).sum())  # 计算向量的1范数
u = torch.ones((2,3))
print(u,'\n',torch.norm(u))

tensor([ 3., -4.]) 
 tensor(5.)
tensor(7.)
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor(2.4495)


## 小结
> 标量、向量、矩阵和张量是线性代数中的基本数学对象。

> 向量泛化自标量，矩阵泛化自向量。

> 标量、向量、矩阵和张量分别具有零、一、二和任意数量的轴。

> 一个张量可以通过sum和mean沿指定的轴降低维度。

> 两个矩阵的按元素乘法被称为他们的哈达玛积。它与矩阵乘法不同。

> 在深度学习中，我们经常使用范数，如 L1 范数、 L2 范数和弗罗贝尼乌斯范数。

> 我们可以对标量、向量、矩阵和张量执行各种操作。

## 小练习
1. 证明一个矩阵 A 的转置的转置是$\mathbf{A}:\left(\mathbf{A}^{\top}\right)^{\top}=\mathbf{A}$
   
   解答：显然成立，将A行分块,然后转置两次 自然复原


2. 给出两个矩阵 A 和 B ，显示转置的和等于和的转置： $\mathbf{A}^{\top}+\mathbf{B}^{\top}=(\mathbf{A}+\mathbf{B})^{\top}$
   
   解答：显然成立 


3. 给定任意方矩阵$\mathbf{A}, \mathbf{A}+\mathbf{A}^{\top}$总是对称的吗? 为什么?
   解答：是的，只需要证明$\mathbf{A}+\mathbf{A}^{\top}$为对称矩阵即可

4. 我们在本节中定义了形状（2,3,4）的张量X。len(X)的输出结果是什么？对于任意形状的张量X, len(X)是否总是对应于X特定轴的长度?这个轴是什么?

In [114]:
X = torch.arange(24).reshape((2,3,4))
len(X) # 输出的始终为张量第0维的长度

2

5. 运行A/A.sum(axis=1)，看看会发生什么。你能分析原因吗？


In [117]:
# A, A/A.sum(axis=1)
# RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

# 原因 A.sum(axis=1) 导致降维 无法广播
# 解决方法 不降维求和(只是第1维的长度压缩为1)
A,A/A.sum(axis=1, keepdims=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]))

6. 当你在曼哈顿的两点之间旅行时，你需要在坐标上走多远，也就是说，就大街和街道而言？你能斜着走吗？
   
   解答 求出两点坐标的曼哈顿距离即可


7. 考虑一个具有形状（2,3,4）的张量，在轴0,1,2上的求和输出是什么形状? 

In [118]:
x7 = torch.arange(24).reshape((2,3,4))
x7, x7.sum(axis=0), x7.sum(axis=1), x7.sum(axis=2)


(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

8. 向linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?
   
   linalg=linear（线性）+algebra（代数），norm则表示范数。



In [127]:
x8 = torch.arange(24).reshape((2,3,4))
x8 = x8.float()
print(x8, '\n',torch.linalg.norm(x8)) # 注意需要为浮点型张量
# 即为 所有元素平方的和的平方根

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]) 
 tensor(65.7571)
