# vscode中jupyter notebook使用技巧

## cell 命令模式快捷键
注: 进入cell命令模式 只需要按`ESC`即可 命令模式下不区分大小写
- `方向键用来操作选中的单元格`
- `Shift+Enter` : 运行本单元，选中或插入（最后一个Cell的时候）下个单元
- `Ctrl+Enter` : 运行本单元
- `Alt+Enter` : 运行本单元，在其下插入新单元
- `Y` : 单元转入代码状态
- `M`:单元转入markdown状态 （目前尚不支持R 原生状态）
- `Enter` : 转入编辑模式
- `A` : 在上方插入新单元
- `B` : 在下方插入新单元
- `DD` : 删除选中的单元
- `L` : 转换行号
- `Shift+Space` : 向上滚动
- `Space` : 向下滚动


In [30]:
# 引入pytorch框架
import torch

x = torch.arange(2,18,2) #创建行向量 从2到18 间隔为2

print(x)

print(x.shape) #获取张量的各个维数

newX = x.reshape((2,2,-1)) #更改x的维数 -1表示按照总元素数 自动推导最后一维的个数

print(newX)

y = torch.zeros((2,3,4)) #创建全零矩阵 维数分别为(2,3,4)

print(y)

z = torch.ones((2,3,4))

print(z)


tensor([ 2,  4,  6,  8, 10, 12, 14, 16])
torch.Size([8])
tensor([[[ 2,  4],
         [ 6,  8]],

        [[10, 12],
         [14, 16]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
